title: "Ed Callahan Tools and Tips"
description: "PowerShell, SQL, and technical tools"
email: ed@edcallahan.com
github_username: EdCallahan

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

url: "https://edcallahan.github.io"

just_the_docs:
  # Enable search
  search_enabled: true
  navigation_depth: 4
  # enable copy of code blocks
  enable_copy_code_button: true

nav_external_links:
  - title: GitHub
    url: https://github.com/EdCallahan
    hide_icon: false
  - title: EdCallahan.com
    url: https://edcallahan.com
    hide_icon: false
  - title: Blufftop Data Services
    url: https://BlufftopDataServices.com
    hide_icon: false