# https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml

title: "Ed Callahan Tools and Tips"
description: "PowerShell, SQL, and technical tools"
email: ed@edcallahan.com
github_username: EdCallahan

theme: just-the-docs

url: "https://edcallahan.github.io"

nav_external_links:
  - title: GitHub
    url: https://github.com/EdCallahan
    hide_icon: false
  - title: EdCallahan.com
    url: https://edcallahan.com
    hide_icon: false
  - title: Blufftop Data Services
    url: https://BlufftopDataServices.com
    hide_icon: false

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
